services:
  memcached:
    image: cloudsuite/data-caching:server
    command: -t 4 -m $SERVER_MEMORY -n 550
    environment:
      - SERVER_MEMORY=$SERVER_MEMORY
    ports:
      - 11211:11211
  cadvisor:
    privileged: true
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    ports:
      - 5050:8080
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - memcached
    expose:
      - '8080'
  prometheus:
    image: prom/prometheus:v2.49.1
    ports:
      - 9090:9090
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus:/prometheus:rw
    depends_on:
      - cadvisor
volumes:
  prometheus:
    external: true
    name: ${MG_PROMETHEUS_VOLUME_NAME}
