services:
  solr:
    build: .
    # network_mode: host
    restart: always
    # Heap Memory, Number of Servers
    command: ${HEAP_MEMORY?Heap memory unset} 1
    environment:
      - HEAP_MEMORY=$HEAP_MEMORY
    ports:
      - 8983:8983
    volumes_from:
      - container:web_search_dataset
    deploy:
      resources:
        limits:
          cpus: ${CPUS?CPUS unset}
  cadvisor:
    privileged: true
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    ports:
      - 5050:8080
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - solr
    expose:
      - '8080'
  prometheus:
    image: prom/prometheus:v2.49.1
    ports:
      - 9090:9090
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus:/prometheus:rw
    depends_on:
      - cadvisor
volumes:
  prometheus:
    external: true
    name: ${MG_PROMETHEUS_VOLUME_NAME}
